/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function prepareDocumentJson(input: string): string

export declare function renderHtml(input: string): string

export declare function renderTckJson(input: string): string
